 void __cdecl fftwf_destroy_plan(fftwf_plan_s *p)
 void __cdecl fftwf_configure_planner(planner_s *)
 void __cdecl fftwf_execute_dft_c2r(fftwf_plan_s *const p, float (*in)[2], float *out)
 void __cdecl fftwf_execute_dft_r2c(fftwf_plan_s *const p, float *in, float (*out)[2])
 void __cdecl fftwf_execute_dft(fftwf_plan_s *const p,	float (*in)[2],	float (*out)[2])
 void __cdecl fftwf_execute_r2r(fftwf_plan_s *const p,	float *in, float *out)
 void __cdecl fftwf_execute_split_dft_c2r(fftwf_plan_s	*const p, float	*ri, float *ii,	float *out)
 void __cdecl fftwf_execute_split_dft_r2c(fftwf_plan_s	*const p, float	*in, float *ro,	float *io)
 void __cdecl fftwf_execute_split_dft(fftwf_plan_s *const p, float *ri, float *ii, float *ro, float *io)
 void __cdecl fftwf_execute(fftwf_plan_s *const p)
 void __cdecl fftwf_export_wisdom_to_file(_iobuf *output_file)
 int __cdecl fftwf_export_wisdom_to_filename(const char *filename)
 char *__cdecl	fftwf_export_wisdom_to_string()
 void __cdecl fftwf_export_wisdom(void	(__cdecl *write_char)(char, void *), void *data)
 void __cdecl fftwf_flops(fftwf_plan_s	*const p, long double *add, long double	*mul, long double *fma)
 long double __cdecl fftwf_estimate_cost(fftwf_plan_s *const p)
 long double __cdecl fftwf_cost(fftwf_plan_s *const p)
 int __cdecl fftwf_import_system_wisdom()
 int __cdecl fftwf_import_wisdom_from_file(_iobuf *input_file)
 int __cdecl fftwf_import_wisdom_from_filename(const char *filename)
 int __cdecl fftwf_import_wisdom_from_string(const char *input_string)
 int __cdecl fftwf_import_wisdom(int (__cdecl *read_char)(void	*), void *data)
 void *__cdecl	fftwf_malloc(unsigned int n)
 void __cdecl fftwf_ifree(void	*p)
 float	*__cdecl fftwf_alloc_real(unsigned int n)
 float	(*__cdecl fftwf_alloc_complex(unsigned int n))[2]
 void __cdecl fftwf_mapflags(planner_s	*plnr, unsigned	int flags)
 printer_s *__cdecl fftwf_mkprinter_file(_iobuf *f)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_1d(int n, float (*in)[2], float (*out)[2], int sign, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_2d(int nx, int ny, float	(*in)[2], float	(*out)[2], int sign, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_3d(int nx, int ny, int nz, float	(*in)[2], float	(*out)[2], int sign, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_c2r_1d(int n, float (*in)[2], float *out, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_c2r_2d(int nx, int ny, float (*in)[2], float *out, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_c2r_3d(int nx, int ny, int nz, float (*in)[2], float *out, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_c2r(int rank, const int *n, float (*in)[2], float *out, unsigned	int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_r2c_1d(int n, float *in,	float (*out)[2], unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_r2c_2d(int nx, int ny, float *in, float (*out)[2], unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_r2c_3d(int nx, int ny, int nz, float *in, float (*out)[2], unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft_r2c(int rank, const int *n, float *in, float (*out)[2], unsigned	int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_dft(int rank, const int *n, float (*in)[2], float (*out)[2],	int sign, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru64_dft_r2c(int rank, fftw_iodim64_do_not_use_me *dims, int howmany_rank,	fftw_iodim64_do_not_use_me *howmany_dims, float	*in, float (*out)[2], unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru_dft(int	rank, fftw_iodim64_do_not_use_me *dims,	int howmany_rank, fftw_iodim64_do_not_use_me *howmany_dims, float (*in)[2], float (*out)[2], int sign, unsigned	int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru_r2r(int	rank, fftw_iodim64_do_not_use_me *dims,	int howmany_rank, fftw_iodim64_do_not_use_me *howmany_dims, float *in, float *out, fftw_r2r_kind_do_not_use_me *kind, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru_split_dft_r2c(int rank,	fftw_iodim64_do_not_use_me *dims, int howmany_rank, fftw_iodim64_do_not_use_me *howmany_dims, float *in, float *ro, float *io, unsigned	int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru64_split_dft(int	rank, fftw_iodim64_do_not_use_me *dims,	int howmany_rank, fftw_iodim64_do_not_use_me *howmany_dims, float *ri, float *ii, float	*ro, float *io,	unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru64_dft_c2r(int rank, fftw_iodim64_do_not_use_me *dims, int howmany_rank,	fftw_iodim64_do_not_use_me *howmany_dims, float	(*in)[2], float	*out, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_guru_split_dft_c2r(int rank,	fftw_iodim64_do_not_use_me *dims, int howmany_rank, fftw_iodim64_do_not_use_me *howmany_dims, float *ri, float *ii, float *out,	unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_many_dft_c2r(int rank, const	int *n,	int howmany, float (*in)[2], const int *inembed, int istride, int idist, float *out, const int *onembed, int ostride, int odist, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_many_dft_r2c(int rank, const	int *n,	int howmany, float *in,	const int *inembed, int	istride, int idist, float (*out)[2], const int *onembed, int ostride, int odist, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_many_dft(int	rank, const int	*n, int	howmany, float (*in)[2], const int *inembed, int istride, int idist, float (*out)[2], const int	*onembed, int ostride, int odist, int sign, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_many_r2r(int	rank, const int	*n, int	howmany, float *in, const int *inembed,	int istride, int idist,	float *out, const int *onembed,	int ostride, int odist,	fftw_r2r_kind_do_not_use_me *kind, unsigned int	flags)
 fftwf_plan_s *__cdecl	fftwf_plan_r2r_1d(int n, float *in, float *out,	fftw_r2r_kind_do_not_use_me kind, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_r2r_2d(int nx, int ny, float	*in, float *out, fftw_r2r_kind_do_not_use_me kindx, fftw_r2r_kind_do_not_use_me	kindy, unsigned	int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_r2r_3d(int nx, int ny, int nz, float	*in, float *out, fftw_r2r_kind_do_not_use_me kindx, fftw_r2r_kind_do_not_use_me	kindy, fftw_r2r_kind_do_not_use_me kindz, unsigned int flags)
 fftwf_plan_s *__cdecl	fftwf_plan_r2r(int rank, const int *n, float *in, float	*out, fftw_r2r_kind_do_not_use_me *kind, unsigned int flags)
 void __cdecl fftwf_fprint_plan(fftwf_plan_s *const p,	_iobuf *output_file)
 void __cdecl fftwf_print_plan(fftwf_plan_s *const p)
 planner_s *__cdecl fftwf_the_planner()
 void __cdecl fftwf_set_timelimit(long	double tlim)
 void __cdecl fftwf_dft_bluestein_register(planner_s *p)
 void __cdecl fftwf_dft_buffered_register(planner_s *p)
 void __cdecl fftwf_ct_generic_register(planner_s *p)
 void __cdecl fftwf_ct_genericbuf_register(planner_s *p)
 void __cdecl fftwf_dft_generic_register(planner_s *p)
 void __cdecl fftwf_dft_indirect_transpose_register(planner_s *p)
 void __cdecl fftwf_dft_indirect_register(planner_s *p)
 void __cdecl fftwf_dft_nop_register(planner_s	*p)
 problem_s *__cdecl fftwf_mkproblem_dft(tensor	*sz, tensor *vecsz, float *ri, float *ii, float	*ro, float *io)
 void __cdecl fftwf_dft_rader_register(planner_s *p)
 void __cdecl fftwf_dft_rank_geq2_register(planner_s *p)
 void __cdecl fftwf_rdft2_solve(plan_s	*ego_, problem_s *p_)
 void __cdecl fftwf_dft_vrank_geq1_register(planner_s *p)
 void __cdecl fftwf_codelet_n1_10(planner_s *p)
 void __cdecl fftwf_codelet_n1_11(planner_s *p)
 void __cdecl fftwf_codelet_n1_12(planner_s *p)
 void __cdecl fftwf_codelet_n1_13(planner_s *p)
 void __cdecl fftwf_codelet_n1_14(planner_s *p)
 void __cdecl fftwf_codelet_n1_15(planner_s *p)
 void __cdecl fftwf_codelet_n1_16(planner_s *p)
 void __cdecl fftwf_codelet_n1_2(planner_s *p)
 void __cdecl fftwf_codelet_n1_20(planner_s *p)
 void __cdecl fftwf_codelet_n1_25(planner_s *p)
 void __cdecl fftwf_codelet_n1_3(planner_s *p)
 void __cdecl fftwf_codelet_n1_32(planner_s *p)
 void __cdecl fftwf_codelet_n1_4(planner_s *p)
 void __cdecl fftwf_codelet_n1_5(planner_s *p)
 void __cdecl fftwf_codelet_n1_6(planner_s *p)
 void __cdecl fftwf_codelet_n1_64(planner_s *p)
 void __cdecl fftwf_codelet_n1_7(planner_s *p)
 void __cdecl fftwf_codelet_n1_8(planner_s *p)
 void __cdecl fftwf_codelet_n1_9(planner_s *p)
 void __cdecl fftwf_codelet_q1_2(planner_s *p)
 void __cdecl fftwf_codelet_q1_3(planner_s *p)
 void __cdecl fftwf_codelet_q1_4(planner_s *p)
 void __cdecl fftwf_codelet_q1_5(planner_s *p)
 void __cdecl fftwf_codelet_q1_6(planner_s *p)
 void __cdecl fftwf_codelet_q1_8(planner_s *p)
 void __cdecl fftwf_codelet_t1_10(planner_s *p)
 void __cdecl fftwf_codelet_t1_12(planner_s *p)
 void __cdecl fftwf_codelet_t1_15(planner_s *p)
 void __cdecl fftwf_codelet_t1_16(planner_s *p)
 void __cdecl fftwf_codelet_t1_2(planner_s *p)
 void __cdecl fftwf_codelet_t1_20(planner_s *p)
 void __cdecl fftwf_codelet_t1_25(planner_s *p)
 void __cdecl fftwf_codelet_t1_3(planner_s *p)
 void __cdecl fftwf_codelet_t1_32(planner_s *p)
 void __cdecl fftwf_codelet_t1_4(planner_s *p)
 void __cdecl fftwf_codelet_t1_5(planner_s *p)
 void __cdecl fftwf_codelet_t1_6(planner_s *p)
 void __cdecl fftwf_codelet_t1_64(planner_s *p)
 void __cdecl fftwf_codelet_t1_7(planner_s *p)
 void __cdecl fftwf_codelet_t1_8(planner_s *p)
 void __cdecl fftwf_codelet_t1_9(planner_s *p)
 void __cdecl fftwf_codelet_t2_10(planner_s *p)
 void __cdecl fftwf_codelet_t2_16(planner_s *p)
 void __cdecl fftwf_codelet_t2_20(planner_s *p)
 void __cdecl fftwf_codelet_t2_25(planner_s *p)
 void __cdecl fftwf_codelet_t2_32(planner_s *p)
 void __cdecl fftwf_codelet_t2_4(planner_s *p)
 void __cdecl fftwf_codelet_t2_5(planner_s *p)
 void __cdecl fftwf_codelet_t2_64(planner_s *p)
 void __cdecl fftwf_codelet_t2_8(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_11_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_128_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_13_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_14_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_15_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_3_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_7_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1bv_9_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_11_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_128_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_13_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_14_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_15_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_3_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_7_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n1fv_9_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_14_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2bv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_14_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2fv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2sv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2sv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2sv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2sv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_n2sv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1bv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1bv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1bv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1bv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1fv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1fv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1fv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_q1fv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_3_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_7_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1buv_9_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_15_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_3_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_7_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1bv_9_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_3_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_7_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fuv_9_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_15_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_3_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_6_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_7_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1fv_9_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1sv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1sv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1sv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1sv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t1sv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2bv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_2_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_64_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2fv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2sv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2sv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2sv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t2sv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3bv_8_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_25_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_4_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_5_sse2(planner_s *p)
 void __cdecl fftwf_codelet_t3fv_8_sse2(planner_s *p)
 void *__cdecl	fftwf_malloc_plain(unsigned int	n)
 void __cdecl fftwf_assertion_failed(const char *s, int line, const char *file)
 void __cdecl fftwf_cpy2d_ci(float *I,	float *O, int n0, int is0, int os0, int	n1, int	is1, int os1, int vl)
 void __cdecl fftwf_cpy2d_co(float *I,	float *O, int n0, int is0, int os0, int	n1, int	is1, int os1, int vl)
 void __cdecl fftwf_cpy2d_tiled(float *I, float *O, int n0, int is0, int os0, int n1, int is1,	int os1, int vl)
 void __cdecl fftwf_cpy2d_tiledbuf(float *I, float *O,	int n0,	int is0, int os0, int n1, int is1, int os1, int	vl)
 int __cdecl fftwf_pickdim(int	which_dim, const int *buddies, int nbuddies, tensor *sz, int oop, int *dp)
 void __cdecl fftwf_plan_awake(plan_s *ego, wakefulness wakefulness)
 planner_s *__cdecl fftwf_mkplanner()
 void __cdecl fftwf_planner_destroy(planner_s *ego)
 int __cdecl fftwf_power_mod(int n, int m, int	p)
 int __cdecl fftwf_find_generator(int p)
 void __cdecl fftwf_printer_destroy(printer_s *p)
 tensor *__cdecl fftwf_mktensor_0d()
 tensor *__cdecl fftwf_mktensor_1d(int	n, int is, int os)
 tensor *__cdecl fftwf_mktensor_2d(int	n0, int	is0, int os0, int n1, int is1, int os1)
 tensor *__cdecl fftwf_mktensor_3d(int	n0, int	is0, int os0, int n1, int is1, int os1,	int n2,	int is2, int os2)
 int __cdecl fftwf_tensor_min_stride(tensor *sz)
 tensor *__cdecl fftwf_tensor_copy(tensor *sz)
 tensor *__cdecl fftwf_tensor_copy_inplace(tensor *sz,	inplace_kind k)
 tensor *__cdecl fftwf_tensor_append(tensor *a, tensor	*b)
 int __cdecl fftwf_dimcmp(iodim *a, iodim *b)
 void __cdecl fftwf_tile2d(int	n0l, int n0u, int n1l, int n1u,	int tilesz, void (__cdecl *f)(int, int,	int, int, void *), void	*args)
 long double __cdecl fftwf_elapsed_since(planner_s *plnr, problem_s *p, int t0)
 void __cdecl fftwf_transpose(float *I, int n,	int s0,	int s1,	int vl)
 void __cdecl fftwf_transpose_tiled(float *I, int n, int s0, int s1, int vl)
 void __cdecl fftwf_transpose_tiledbuf(float *I, int n, int s0, int s1, int vl)
 triggen_s *__cdecl fftwf_mktriggen(wakefulness wakefulness, int n)
 void __cdecl fftwf_rdft_buffered_register(planner_s *p)
 void __cdecl fftwf_rdft2_buffered_register(planner_s *p)
 plan_s *__cdecl fftwf_mkplan_hc2c(unsigned int size, plan_adt	*adt, void (__cdecl *apply)(plan_s *, float *, float *))
 void __cdecl fftwf_dft_r2hc_register(planner_s *p)
 void __cdecl fftwf_dht_r2hc_register(planner_s *p)
 void __cdecl fftwf_dht_rader_register(planner_s *p)
 solver_s *__cdecl fftwf_mksolver_rdft_r2r_direct(void	(__cdecl *k)(const float *, float *, int *, int	*, int,	int, int), kr2r_desc_s *desc)
 solver_s *__cdecl fftwf_mksolver_rdft2_direct(void (__cdecl *k)(float	*, float *, float *, float *, int *, int *, int	*, int,	int, int), kr2c_desc_s *desc)
 void __cdecl fftwf_rdft_generic_register(planner_s *p)
 void __cdecl fftwf_hc2hc_generic_register(planner_s *p)
 void __cdecl fftwf_rdft_indirect_register(planner_s *p)
 void __cdecl fftwf_rdft_nop_register(planner_s *p)
 void __cdecl fftwf_rdft2_nop_register(planner_s *p)
 plan_s *__usercall fftwf_mkplan_dft<eax>(unsigned int	size<eax>, plan_adt *adt, void (__cdecl	*apply)(plan_s *, float	*, float *, float *, float *))
 problem_s *__cdecl fftwf_mkproblem_rdft(tensor *sz, tensor *vecsz, float *I, float *O, rdft_kind *kind)
 problem_s *__cdecl fftwf_mkproblem_rdft2(tensor *sz, tensor *vecsz, float *r0, float *r1, float *cr, float *ci, rdft_kind kind)
 void __cdecl fftwf_rdft2_rank_geq2_register(planner_s	*p)
 void __cdecl fftwf_rdft_rank_geq2_register(planner_s *p)
 void __cdecl fftwf_rdft2_rank0_register(planner_s *p)
 void __cdecl fftwf_rdft_rank0_register(planner_s *p)
 void __cdecl fftwf_rdft_dht_register(planner_s *p)
 int __cdecl fftwf_rdft2_inplace_strides(problem_rdft2	*p, int	vdim)
 void __cdecl fftwf_rdft2_rdft_register(planner_s *p)
 int __cdecl fftwf_rdft2_tensor_max_index(tensor *sz, rdft_kind k)
 void __cdecl fftwf_rdft_solve(plan_s *ego_, problem_s	*p_)
 void __cdecl fftwf_rdft2_vrank_geq1_register(planner_s *p)
 void __cdecl fftwf_rdft_vrank_geq1_register(planner_s	*p)
 void __cdecl fftwf_rdft_vrank3_transpose_register(planner_s *p)
 void __cdecl fftwf_codelet_hb2_16(planner_s *p)
 void __cdecl fftwf_codelet_hb2_20(planner_s *p)
 void __cdecl fftwf_codelet_hb2_25(planner_s *p)
 void __cdecl fftwf_codelet_hb2_32(planner_s *p)
 void __cdecl fftwf_codelet_hb2_4(planner_s *p)
 void __cdecl fftwf_codelet_hb2_5(planner_s *p)
 void __cdecl fftwf_codelet_hb2_8(planner_s *p)
 void __cdecl fftwf_codelet_hb_10(planner_s *p)
 void __cdecl fftwf_codelet_hb_12(planner_s *p)
 void __cdecl fftwf_codelet_hb_15(planner_s *p)
 void __cdecl fftwf_codelet_hb_16(planner_s *p)
 void __cdecl fftwf_codelet_hb_2(planner_s *p)
 void __cdecl fftwf_codelet_hb_20(planner_s *p)
 void __cdecl fftwf_codelet_hb_25(planner_s *p)
 void __cdecl fftwf_codelet_hb_3(planner_s *p)
 void __cdecl fftwf_codelet_hb_32(planner_s *p)
 void __cdecl fftwf_codelet_hb_4(planner_s *p)
 void __cdecl fftwf_codelet_hb_5(planner_s *p)
 void __cdecl fftwf_codelet_hb_6(planner_s *p)
 void __cdecl fftwf_codelet_hb_64(planner_s *p)
 void __cdecl fftwf_codelet_hb_7(planner_s *p)
 void __cdecl fftwf_codelet_hb_8(planner_s *p)
 void __cdecl fftwf_codelet_hb_9(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb2_16(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb2_20(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb2_32(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb2_4(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cb2_8(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cbdft2_16(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft2_20(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft2_32(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft2_4(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft2_8(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_10(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_12(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_16(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_20(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_32(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_4(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_6(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdft_8(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb_10(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cb_12(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cb_16(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cb_2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb_20(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cb_32(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cb_4(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb_6(planner_s *p)
 void __cdecl fftwf_codelet_hc2cb_8(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_10(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_12(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_15(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_16(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_2(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_20(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_25(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_3(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_32(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_4(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_5(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_6(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_64(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_7(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_8(planner_s *p)
 void __cdecl fftwf_codelet_r2cbIII_9(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_10(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_11(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_12(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_128(planner_s	*p)
 void __cdecl fftwf_codelet_r2cb_13(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_14(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_15(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_16(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_2(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_20(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_25(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_3(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_32(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_4(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_5(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_6(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_64(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_7(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_8(planner_s *p)
 void __cdecl fftwf_codelet_r2cb_9(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf2_16(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf2_20(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf2_32(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf2_4(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cf2_8(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cfdft2_16(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft2_20(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft2_32(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft2_4(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft2_8(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_10(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_12(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_16(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_20(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_32(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_4(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_6(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdft_8(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf_10(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cf_12(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cf_16(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cf_2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf_20(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cf_32(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cf_4(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf_6(planner_s *p)
 void __cdecl fftwf_codelet_hc2cf_8(planner_s *p)
 void __cdecl fftwf_codelet_hf2_16(planner_s *p)
 void __cdecl fftwf_codelet_hf2_20(planner_s *p)
 void __cdecl fftwf_codelet_hf2_25(planner_s *p)
 void __cdecl fftwf_codelet_hf2_32(planner_s *p)
 void __cdecl fftwf_codelet_hf2_4(planner_s *p)
 void __cdecl fftwf_codelet_hf2_5(planner_s *p)
 void __cdecl fftwf_codelet_hf2_8(planner_s *p)
 void __cdecl fftwf_codelet_hf_10(planner_s *p)
 void __cdecl fftwf_codelet_hf_12(planner_s *p)
 void __cdecl fftwf_codelet_hf_15(planner_s *p)
 void __cdecl fftwf_codelet_hf_16(planner_s *p)
 void __cdecl fftwf_codelet_hf_2(planner_s *p)
 void __cdecl fftwf_codelet_hf_20(planner_s *p)
 void __cdecl fftwf_codelet_hf_25(planner_s *p)
 void __cdecl fftwf_codelet_hf_3(planner_s *p)
 void __cdecl fftwf_codelet_hf_32(planner_s *p)
 void __cdecl fftwf_codelet_hf_4(planner_s *p)
 void __cdecl fftwf_codelet_hf_5(planner_s *p)
 void __cdecl fftwf_codelet_hf_6(planner_s *p)
 void __cdecl fftwf_codelet_hf_64(planner_s *p)
 void __cdecl fftwf_codelet_hf_7(planner_s *p)
 void __cdecl fftwf_codelet_hf_8(planner_s *p)
 void __cdecl fftwf_codelet_hf_9(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_10(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_12(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_15(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_16(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_2(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_20(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_25(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_3(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_32(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_4(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_5(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_6(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_64(planner_s *p)
 void __cdecl fftwf_codelet_r2cfII_7(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_8(planner_s	*p)
 void __cdecl fftwf_codelet_r2cfII_9(planner_s	*p)
 void __cdecl fftwf_codelet_r2cf_10(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_11(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_12(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_128(planner_s	*p)
 void __cdecl fftwf_codelet_r2cf_13(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_14(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_15(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_16(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_2(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_20(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_25(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_3(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_32(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_4(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_5(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_6(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_64(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_7(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_8(planner_s *p)
 void __cdecl fftwf_codelet_r2cf_9(planner_s *p)
 void __cdecl fftwf_codelet_e01_8(planner_s *p)
 void __cdecl fftwf_codelet_e10_8(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdftv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdftv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdftv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdftv_2_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cbdftv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdftv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cbdftv_4_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cbdftv_6_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cbdftv_8_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cfdftv_10_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdftv_12_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdftv_16_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdftv_2_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cfdftv_20_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdftv_32_sse2(planner_s *p)
 void __cdecl fftwf_codelet_hc2cfdftv_4_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cfdftv_6_sse2(planner_s	*p)
 void __cdecl fftwf_codelet_hc2cfdftv_8_sse2(planner_s	*p)
 void __cdecl fftwf_redft00e_r2hc_pad_register(planner_s *p)
 void __cdecl fftwf_reodft00e_splitradix_register(planner_s *p)
 void __cdecl fftwf_reodft010e_r2hc_register(planner_s	*p)
 void __cdecl fftwf_reodft11e_r2hc_odd_register(planner_s *p)
 void __cdecl fftwf_reodft11e_radix2_r2hc_register(planner_s *p)
 void __cdecl fftwf_rodft00e_r2hc_pad_register(planner_s *p)
 int __cdecl fftwf_have_simd_sse2()
 int __cdecl fftwf_init_threads()
 void __cdecl fftwf_plan_with_nthreads(int nthreads)
 ct_solver_s *__cdecl fftwf_mksolver_ct_threads(unsigned int size, int	r, int dec, plan_s *(__cdecl *mkcldw)(ct_solver_s *, int, int, int, int, int, int, int,	int, int, int, float *,	float *, planner_s *), int (__cdecl *force_vrecursionp)(ct_solver_s *, problem_dft *))
 void __cdecl fftwf_dft_thr_vrank_geq1_register(planner_s *p)
 hc2hc_solver_s *__cdecl fftwf_mksolver_hc2hc_threads(unsigned	int size, int r, plan_s	*(__cdecl *mkcldw)(hc2hc_solver_s *, rdft_kind,	int, int, int, int, int, int, int, float *, planner_s *))
 void __usercall fftwf_spawn_loop(int loopmax<esi>, int nthr<ecx>, void *(__cdecl *proc)(spawn_data *), void *data)
 void __cdecl fftwf_rdft_thr_vrank_geq1_register(planner_s *p)
 void __cdecl fftwf_rdft2_thr_vrank_geq1_register(planner_s *p)
